<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblEthereum</name>
   <tag></tag>
   <elementGuidId>66adc2d0-df9b-45c3-a5ef-b43ad2898295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-coin-overview']/div/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-65e7f566-0.lsTl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23a32406-b733-4ca7-8dfc-65a7c2d649ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>coin-name</value>
      <webElementGuid>8f8ff6c9-a6b0-46a9-ae1b-36e438c732c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ethereum</value>
      <webElementGuid>4cc6354b-cbf5-4fe6-9693-ea9dfdb4cc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-65e7f566-0 lsTl</value>
      <webElementGuid>ad10dc09-f3a8-45e9-bf64-59b6c62d8cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ethereum price</value>
      <webElementGuid>36a09554-8880-4c4a-97d6-99b0857749df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-coin-overview&quot;)/div[@class=&quot;sc-65e7f566-0 gLzlll&quot;]/h1[@class=&quot;sc-65e7f566-0 hIeodp&quot;]/span[@class=&quot;sc-65e7f566-0 lsTl&quot;]</value>
      <webElementGuid>e012e8b0-4057-4b2e-b1c1-71ed1ada8164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-coin-overview']/div/h1/span</value>
      <webElementGuid>3bb0fb2c-1361-43af-93e0-f7d705fa4387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Diamonds'])[1]/following::span[1]</value>
      <webElementGuid>4f572b6c-43c7-4c16-861c-d24983892775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[1]/following::span[1]</value>
      <webElementGuid>a4816d4c-f60c-430d-a8b4-f1cd40b38df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETH'])[1]/preceding::span[2]</value>
      <webElementGuid>d8dcb608-930c-4119-850a-b94706a29d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ethereum']/parent::*</value>
      <webElementGuid>07800ba8-dea6-49fd-99bc-ed1f3e09fb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>5a94ffc2-0631-4d08-a9a7-0993d2cc3013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Ethereum' and (text() = 'Ethereum price' or . = 'Ethereum price')]</value>
      <webElementGuid>e5b84476-9bc9-4d39-855e-140f59f448ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
