<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblXRP</name>
   <tag></tag>
   <elementGuidId>b30aea61-5b8b-42f3-90b5-9f1e2c89568f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-coin-overview']/div/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-65e7f566-0.lsTl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>256bc8d8-3779-4b1c-a4a3-74041b2fce4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>coin-name</value>
      <webElementGuid>34cb78b4-6222-409f-9756-1ee6226e6d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>XRP</value>
      <webElementGuid>965a1772-b543-4c05-8c1b-8ece8876d832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-65e7f566-0 lsTl</value>
      <webElementGuid>8de6fb92-5fd1-4f0f-8975-4ad12841e8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XRP price</value>
      <webElementGuid>4041e937-5c1a-490c-8c94-129eaf91dc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-coin-overview&quot;)/div[@class=&quot;sc-65e7f566-0 gLzlll&quot;]/h1[@class=&quot;sc-65e7f566-0 hIeodp&quot;]/span[@class=&quot;sc-65e7f566-0 lsTl&quot;]</value>
      <webElementGuid>6be9e96e-9ec5-4b94-88e5-bbe835675416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-coin-overview']/div/h1/span</value>
      <webElementGuid>98986f5c-16ae-4ca5-a314-0cab3d77542b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Diamonds'])[1]/following::span[1]</value>
      <webElementGuid>aa650caa-ad45-420e-b5ba-1607274dcb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[1]/following::span[1]</value>
      <webElementGuid>f253e564-d793-44fe-89f1-127c493048cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XRP'])[1]/preceding::span[2]</value>
      <webElementGuid>7d9d9a4d-bac8-4b06-ab3d-8d6526d6b927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='XRP']/parent::*</value>
      <webElementGuid>1fd3908d-ad64-4139-a4a7-30f3c526c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>1fa50feb-83ab-4a58-b73a-7652dc42599d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'XRP' and (text() = 'XRP price' or . = 'XRP price')]</value>
      <webElementGuid>bd94371d-683f-4323-8ca8-b5ee830b1500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
