<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBarInput</name>
   <tag></tag>
   <elementGuidId>9db72f90-56f3-4d3c-a89a-111199bc1a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-951d4f56-3.gNFMEo.search-input.desktop-input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @placeholder = 'Search coin, pair, NFT, contract address, exchange, or post']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5593952-9df0-4150-b900-c0703efddc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0810cbae-c816-41fc-b353-a5a3b58fa39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>deadad1b-b41b-46aa-bc04-ea3ad959fa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-951d4f56-3 gNFMEo search-input desktop-input</value>
      <webElementGuid>4b5842a9-63df-413e-ad34-f09f6789f7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>236e38a1-0421-4982-8aa0-acb65c7898ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search coin, pair, NFT, contract address, exchange, or post</value>
      <webElementGuid>b0e95ba8-05f7-48d1-b25e-1408b462447b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>XRP</value>
      <webElementGuid>ef297673-9fa8-4f64-8eb4-6b369379c895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;DAY NIGHT common-overflow&quot;]/div[3]/div[6]/div[@class=&quot;Overlay_base__X2QP3 Modal_overlay__wGYev overlay-fade-enter-done&quot;]/div[@class=&quot;Modal_wrapper__KLeg2 Modal_mobile-fullscreen__nSEhF Search_modal-wrapper__WlBGJ&quot;]/div[@class=&quot;modal-body-wrapper Modal_dialog-body-wrapper__G4CTp Modal_dialog-common-wrapper-space__9oWxL&quot;]/div[@class=&quot;sc-951d4f56-0 bFgTgh Search_container__THKkg Search_dark-mode___XGR_&quot;]/div[@class=&quot;sc-951d4f56-1 fNZpMt search-box&quot;]/div[@class=&quot;sc-951d4f56-2 hPmeav&quot;]/input[@class=&quot;sc-951d4f56-3 gNFMEo search-input desktop-input&quot;]</value>
      <webElementGuid>06a2d671-0c9e-499b-8580-2cd9f7dc24d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='XRP']</value>
      <webElementGuid>edcfa7fe-84a1-43bc-8499-52bfe35aec86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/input</value>
      <webElementGuid>d81235bd-fdcf-4942-a522-ba50ee9ca9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search coin, pair, NFT, contract address, exchange, or post']</value>
      <webElementGuid>0e471b32-acb0-41fa-aed4-804e69983f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
