<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBar</name>
   <tag></tag>
   <elementGuidId>902a62f1-9b43-41c0-8602-2b2b68b0eb5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='My Diamonds'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.sc-65e7f566-0.eyXrOz.c-i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9c7f888d-09e3-4e0d-a048-e37e313c29f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>252b4188-bf40-411b-b228-88bbc28c7236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>bc790d84-c31f-444d-bb50-f6619bfb3bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>2e996a05-7469-4bc1-beba-f82c8213803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>0fe12b8f-03a9-44c1-89d2-bcbee8bded9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>d2fcc353-6f32-43fe-912c-5893010372eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-65e7f566-0 eyXrOz c-i</value>
      <webElementGuid>3e8d3c72-32ca-43b9-a85e-fac1516d18d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e6c8a3eb-5666-4c02-868f-44cd797f9ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decode</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0c0b9b9f-072f-4d58-9ae5-fd16a35f9d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>priority</name>
      <type>Main</type>
      <value>low</value>
      <webElementGuid>0e9139a2-8574-4545-93f5-05e7c3ad121f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sc-7c7f3865-1 hhqoRw global-layout-v2&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;sc-7c7f3865-0 jZHXCc&quot;]/div[@class=&quot;HeaderV3_global-header__Rdkas&quot;]/div[@class=&quot;HeaderV3_main-header__xTs_o&quot;]/div[@class=&quot;HeaderV3_main-header-left__bUVZv&quot;]/div[@class=&quot;sc-29b0e71f-0 cDmmUH&quot;]/div[@class=&quot;Search_mobile-icon-wrapper__95svj&quot;]/svg[@class=&quot;sc-65e7f566-0 eyXrOz c-i&quot;]</value>
      <webElementGuid>b230d227-a31f-4346-b17a-97a0bf464af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Diamonds'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>7e00f391-3735-4129-8e38-ee925405c13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0b60a25c-6dd4-41e2-8341-5a036fea8e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2.61T'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>ca582827-674f-4115-a9da-b63cc0b52ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
