<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>prod1Price</name>
   <tag></tag>
   <elementGuidId>e5643b78-2e3c-46b3-b81b-d754c33cec6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(8) > p.sc-71024e3e-0.fOLOxZ > span.sc-11478e5d-1.jfwGHx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div/div/div[5]/div/table/tbody/tr[2]/td[8]/p/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a242f560-b840-4a78-b8e5-32cdab65b55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nosnippet</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ac2ae36-5be3-4c53-9db3-2be12c3738b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-11478e5d-1 jfwGHx</value>
      <webElementGuid>c7ae66f2-0f65-4303-98b4-306f73a97bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$41</value>
      <webElementGuid>d71d2a35-d16b-4c8f-9076-b579a57ec79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sc-7c7f3865-1 hhqoRw global-layout-v2&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;cmc-body-wrapper&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;sc-aaad5b7-2 fqornS&quot;]/div[5]/div[@class=&quot;sc-db1da501-2 chNJPK&quot;]/table[@class=&quot;sc-db1da501-3 kTEDDd cmc-table&quot;]/tbody[1]/tr[2]/td[8]/p[@class=&quot;sc-71024e3e-0 fOLOxZ&quot;]/span[@class=&quot;sc-11478e5d-1 jfwGHx&quot;]</value>
      <webElementGuid>7ada9593-4f5e-4f14-89ab-b5ca62ef652e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div/div/div[5]/div/table/tbody/tr[2]/td[8]/p/span[2]</value>
      <webElementGuid>18dcdc1b-ab24-4506-9dad-467e9a2706d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40.91'])[1]/following::span[1]</value>
      <webElementGuid>be302f9d-a5e3-486b-973e-6724a7e48a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$41']/parent::*</value>
      <webElementGuid>ed4085e6-4fa8-41d4-8b2b-e786aca329b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/p/span[2]</value>
      <webElementGuid>a5851a7c-cfe3-4e4d-b225-af50f6d4d335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$41' or . = '$41')]</value>
      <webElementGuid>f1c4a4f1-e2d1-4ed3-80ba-ee0178fcee15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
