<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>prod2Price</name>
   <tag></tag>
   <elementGuidId>0da30623-d128-4e6c-b65c-1d7774c8a2bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sc-11478e5d-1.jfwGHx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div/div/div[5]/div/table/tbody/tr/td[8]/p/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b7054d6-2177-4aab-81b3-74bb0f304a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nosnippet</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2989670d-ba55-40a2-978b-43f1dfd602f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-11478e5d-1 jfwGHx</value>
      <webElementGuid>05fb4f46-2c2a-4a51-81c8-408c219d08de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$100</value>
      <webElementGuid>3466c2d9-e17d-4f1f-9588-e228dc5f0eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sc-7c7f3865-1 hhqoRw global-layout-v2&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;cmc-body-wrapper&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;sc-aaad5b7-2 fqornS&quot;]/div[5]/div[@class=&quot;sc-db1da501-2 chNJPK&quot;]/table[@class=&quot;sc-db1da501-3 kTEDDd cmc-table&quot;]/tbody[1]/tr[1]/td[8]/p[@class=&quot;sc-71024e3e-0 fOLOxZ&quot;]/span[@class=&quot;sc-11478e5d-1 jfwGHx&quot;]</value>
      <webElementGuid>f5a6657d-cb1b-40b6-ab8c-75dd0b440a01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div/div/div[5]/div/table/tbody/tr/td[8]/p/span[2]</value>
      <webElementGuid>eef00d9d-75c2-4eb5-ae3e-d38591a17ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$99.93'])[1]/following::span[1]</value>
      <webElementGuid>a01352a9-a39b-4a03-9679-fa1bd367d3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/preceding::span[1]</value>
      <webElementGuid>b5cfc024-0455-431a-af88-0ea6513a57a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$100']/parent::*</value>
      <webElementGuid>03f653f6-db68-48bb-8e34-a0081d80a969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/p/span[2]</value>
      <webElementGuid>73ef775c-4acd-4fc3-928d-a05eb3fb2d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$100' or . = '$100')]</value>
      <webElementGuid>e6a8b4db-3883-4d10-a302-f5c1ca684ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
