<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMax</name>
   <tag></tag>
   <elementGuidId>ea4bebba-1065-47bb-8803-7bd1907e92c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Max' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd36a56-ad20-4330-9f09-7d95e8c92889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmc-input input-el</value>
      <webElementGuid>705d277b-2d82-47a4-a9ad-cdb05303d9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Max</value>
      <webElementGuid>2ae404e2-9527-4616-a6e3-17a1a851a1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e02951d-2afd-4e1d-bc88-be051ad754a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>676dd889-c3c2-4296-b8a1-a116579fcbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;DAY NIGHT common-overflow&quot;]/div[3]/div[2]/div[@class=&quot;Overlay_base__X2QP3 Modal_overlay__wGYev overlay-fade-enter-done&quot;]/div[@class=&quot;Modal_wrapper__KLeg2 Modal_mobile-fullscreen__nSEhF TableListingFilterModal_modal-wrapper__MzBWs&quot;]/div[@class=&quot;modal-body-wrapper Modal_dialog-body-wrapper__G4CTp Modal_dialog-common-wrapper-space__9oWxL&quot;]/div[@class=&quot;Form_form__YA6g_ TableListingFilterModal_form__JrfpJ&quot;]/div[@class=&quot;Form_form-item__xR_Oa form-item&quot;]/div[@class=&quot;Form_field-container__ovGrK&quot;]/div[@class=&quot;RangeFormItem_container__PK9re&quot;]/div[@class=&quot;BaseInput_base-wrapper__QXTyE BaseInput_size-sm__z0vCT Input_base__9dFSw Input_vd__b8IjZ RangeFormItem_input__v7eJ5 BaseInput_vd__yZx2O&quot;]/div[@class=&quot;BaseInput_input-wrapper__wWV3S native-el-wrapper&quot;]/input[@class=&quot;cmc-input input-el&quot;]</value>
      <webElementGuid>e3dbe2cd-6217-4101-a802-d27e344887fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='100']</value>
      <webElementGuid>89e97517-0d1d-4c84-b49f-25dab549df28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>caea9e58-345d-4a4f-80e2-16f362001d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Max' and @type = 'text']</value>
      <webElementGuid>f72130d0-2b9c-4cc5-a626-30c8f09d0f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
